-- 05/09/2021 11:06:11
ALTER TABLE `resultado` ENGINE = InnoDB;

ALTER TABLE `resultado`
		ADD CONSTRAINT `fk_resultado-meta`
		FOREIGN KEY (id_meta)
		REFERENCES meta(id)
			ON UPDATE CASCADE ON DELETE RESTRICT;