-- 17-08-2021 11:07:02
ALTER TABLE `resultado` ENGINE = InnoDB;

ALTER TABLE `resultado`
		ADD CONSTRAINT `fk_resultado-meta`
		FOREIGN KEY (id_meta)
		REFERENCES meta(id)
			ON UPDATE CASCADE ON DELETE RESTRICT;