-- 13-08-2021 15:14:54
CREATE TABLE IF NOT EXISTS _log_acesso (
	id INT(11) PRIMARY KEY AUTO_INCREMENT,
	id_usuario INT(11) NOT NULL,
	sucesso TINYINT(1) NOT NULL,
	ip VARCHAR(15) NOT NULL,
	navegador VARCHAR(400) NOT NULL,
	datahora TIMESTAMP NOT NULL DEFAULT current_timestamp(),
INDEX (id)
);